#!/usr/bin/env bash


## a question that asks if you want to install gish or py-gish or if you don't want to.
echo "(1) install py-gish
(2) install gish
(3) exit"



read question
if [ "$question" == "1" ]; then
	git clone https://github.com/xxhexisxx/py-gish.git
	mv py-gish ~/py-gish_ && mv py-gish_/py-gish ~/ && sleep 1 && chmod +x py-gish && sleep 1 && echo alias py-gish='./py-gish' >> .bashrc && sleep 1
	source .bashrc

fi




if [ "$question" == "2" ]; then
	git clone https://github.com/xxhexisxx/gish_.git
	mv ~/gish_ ~/gish- && sleep 1 && mv ~/gish-/gish ~/ && sleep 1 && chmod +x gish && sleep 1 && echo alias gish='./gish' >> .bashrc && sleep 1 && source .bashrc

fi





if [ "$question" == "3" ]; then
	echo quiting. ; exit
fi




echo "installing please wait" && sleep 2







echo "to start gish type gish in the terminal or if you installed py-gish type py-gish in the terminal. and before you try to use gish type source .bashrc so gish or py-gish can start."





## a question that asks if you want to remove the installer or not.
echo "do you want to remove the gish-installer? (y/n)"




read question2
if [ "$question2" == "y" ]; then
        rm gish-installer && echo "thank you for installing gish :)"
fi





if [ "$question2" == "n" ]; then
	echo okay quiting. ; sleep 1 ; echo "thank you for installing gish :)" ; exit
fi
