#!/usr/bin/env bash


## a question that asks if you want to install multis or multis-py or if you don't want to.
echo "(1) install multis-py
(2) install multis
(3) exit"



read question
if [ "$question" == "1" ]; then
	git clone https://github.com/xxhexisxx/py-gish.git
	mv py-gish ~/py-gish_ && mv py-gish_/py-gish ~/ && sleep 1 && chmod +x py-gish && sleep 1 && echo alias py-gish='./py-gish' >> .bashrc && sleep 1
	source .bashrc

fi




if [ "$question" == "2" ]; then
	git clone https://github.com/xxhexisxx/gish_.git
	mv ~/gish_ ~/gish- && sleep 1 && mv ~/gish-/gish ~/ && sleep 1 && chmod +x gish && sleep 1 && echo alias gish='./gish' >> .bashrc && sleep 1 && source .bashrc

fi





if [ "$question" == "3" ]; then
	echo quiting. ; exit
fi




echo "installing please wait" && sleep 2







echo "to start multis type multis in the terminal or if you installed multis-py type multis-py in the terminal."





## a question that asks if you want to remove the installer or not.
echo "do you want to remove the multis-installer? (y/n)"




read question2
if [ "$question2" == "y" ]; then
        rm gish-installer && echo "thank you for installing multis :)"
fi





if [ "$question2" == "n" ]; then
	echo okay quiting. ; sleep 1 ; echo "thank you for installing multis :)" ; exit
fi
